resources:
- name: hello-from
  type: git
  source:
    uri: {{github-uri}}
    branch: master
    private_key: {{github-private-key}}

- name: hello-from-image
  type: docker-image
  source: 
    repository: richardkdrew/hello-from
    username: {{dockerhub-user}}
    password: {{dockerhub-password}}

- name: go-image
  type: docker-image
  source:
    repository: golang
    tag: '1.6'

jobs:
- name: build
  public: true
  plan:
  - aggregate:
    - get: hello-from
      trigger: true
    - get: go-image
      params: {save: true}
  - task: build
    config:
      platform: linux

      image_resource:
        type: docker-image
        source:
          repository: golang
          version: 1.6

      inputs:
       - name: hello-from

      outputs:
       - name: app

      run:
        path: bash
        args:
        - -c
        - |
          set -e -x
          
          workingFolder=$PWD/hello-from
          output=$PWD/app

          export GOOS=linux GOARCH=amd64

          cd $workingFolder

          go build hello-from.go

          cp $workingFolder/hello-from $workingFolder/Dockerfile $output
  - put: hello-from-image
    params: 
      build: app
      load_base: go-image
      tag_as_latest: true    
